### ISSUE TITLE
Massive gap between apply now and contact section

### ISSUE THREAD

**Issue by harper39** [SpartaHack/SpartaHack2016-Website#11]
Words and logo merged together as shown in picture.

Using an IPad Mini 1/2.

![img_0024](https://github-cloud.s3.amazonaws.com/assets%2F9110491%2F10956584%2Fb8618666-832a-11e5-9f39-e05c164eb90a.PNG)

**Comment by bogderp** [comment]
This has been fixed, iOS doesn't like vh and vw
