### ISSUE TITLE
high school students can still enter field of study and year of school

### ISSUE THREAD

**Issue by daniellescherr** [SpartaHack/SpartaHack2016-Website#18]
we talked about this, probably unnecessary
<img width="580" alt="screen shot 2015-11-04 at 7 37 59 pm" src="https://github-cloud.s3.amazonaws.com/assets%2F11857236%2F10956710%2Fc521603c-832b-11e5-8d0c-d76e98cb0e6d.png">

**Comment by bogderp** [comment]
Corrected on d.spartahack now
