### ISSUE TITLE
text display

### ISSUE THREAD

**Issue by daniellescherr** [SpartaHack/SpartaHack2016-Website#2]
On mac using safari.
Went to apply, entered email and password. Text field prompt is as shown
<img width="678" alt="screen shot 2015-11-04 at 7 21 09 pm" src="https://cloud.githubusercontent.com/assets/11857236/10956402/5f1f8fc2-8329-11e5-8233-f265d7884f71.png">

**Comment by bogderp** [comment]
This is a flaw with Apple's Safari. It appears no css can modify those type of elements.
