### ISSUE TITLE
A few different issues visible in photo on IPad mini

### ISSUE THREAD

**Issue by harper39** [SpartaHack/SpartaHack2016-Website#21]
![img_0025](https://github-cloud.s3.amazonaws.com/assets%2F9110491%2F10956791%2F8c8140f2-832c-11e5-92d5-0db8fc0ee57c.PNG)
![img_0026](https://github-cloud.s3.amazonaws.com/assets%2F9110491%2F10956792%2F8c8ca2e4-832c-11e5-9e78-2da33e62e454.PNG)
![img_0027](https://github-cloud.s3.amazonaws.com/assets%2F9110491%2F10956794%2F8c8d74bc-832c-11e5-99cc-cd3ad2904622.PNG)
![img_0028](https://github-cloud.s3.amazonaws.com/assets%2F9110491%2F10956795%2F8c8d8060-832c-11e5-8683-0d248d26281d.PNG)
![img_0029](https://github-cloud.s3.amazonaws.com/assets%2F9110491%2F10956793%2F8c8d5536-832c-11e5-9c74-e6cb56ea2db6.PNG)

**Comment by bogderp** [comment]
header moving, not sure if i fixed it, but i tried. let me know
moving popup fixed
last picture, page didnt load completely, still loading =P

**Comment by bogderp** [comment]
I believe everything has been patched
