### ISSUE TITLE
When you sign up to be a volunteer and don't input a valid email, it's not obvious whether it submits

### ISSUE THREAD

**Issue by laurenbretz** [SpartaHack/SpartaHack2016-Website#22]
I input my first and last name as "ghjkvhgj" and "hjgsdkf", and my email as "fghjk@gfchvj", clicked submit, and the website reloaded with this warning "You must include a valid email."
It's not clear that there's an error; you should make it very obvious is a form submission is invalid. Have a pop-up or write the error in red or something.

![screen shot 2015-11-04 at 7 46 37 pm](https://github-cloud.s3.amazonaws.com/assets%2F4753114%2F10956834%2Fdac853cc-832c-11e5-8480-f5b63b4d9769.png)

**Comment by bogderp** [comment]
fixed, errors are now red
