### ISSUE TITLE
"Click here" on verified page hard links to "www.spartahack.com/app"

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Website#27]
no such page exists on www.spartahack.com and if it did it would still be broken on d.spartahack.com

maybe replace with "/app" or somesuch

**Comment by bogderp** [comment]
Can't do that, its hard coded because Parse doesn't let me open "/app" since that is a parse page i've styled. it needs to open in a new tab. 

additionally hard coded to www.spartahack.com/app because i dont want to have to submit a commit just for that after the merge.

**Comment by mhammerly** [comment]
what on earth is parse doing injecting itself into our application routes it's a database api not an mvc framework

okay #wontfix
