### ISSUE TITLE
font weight seems to change between fields

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Website#29]
![screenshot](https://cloud.githubusercontent.com/assets/1198161/11483422/43e826fe-9776-11e5-905f-df9d99f67808.png)

note how the 'name' fields are slightly dimmer than others

**Comment by mhammerly** [comment]
again, firefox 42 on linux

**Comment by mhammerly** [comment]
on chrome it is the same brightness as the rest of the form, but i've now noticed it is a different font

**Comment by bogderp** [comment]
fixed yo
