### ISSUE TITLE
font not loaded in "ComPANY LOgo" svg on admin portal

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Website#30]
![screenshot](https://cloud.githubusercontent.com/assets/1198161/11632303/814ff23e-9cd4-11e5-972e-a73600610cf2.png)
lol

firefox 42 linux

**Comment by bogderp** [comment]
Fixed in 7374c3a00b5bc9e007cfb0273a095aa4756db488
