### ISSUE TITLE
queries in the admin actions capped at 1000 records

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Website#35]
we don't want that. set a limit we won't hit, like 5k

https://github.com/SpartaHack/SpartaHack2016-Website/blob/6a6436460139cb0c44cb03e0880b94a67d360d7a/app/controllers/admin_controller.rb#L18
https://github.com/SpartaHack/SpartaHack2016-Website/blob/6a6436460139cb0c44cb03e0880b94a67d360d7a/app/controllers/admin_controller.rb#L22
https://github.com/SpartaHack/SpartaHack2016-Website/blob/6a6436460139cb0c44cb03e0880b94a67d360d7a/app/controllers/admin_controller.rb#L133

i might suggest using a `const QUERY_LIMIT = 5000`or whatever is conventional in ruby so as to avoid having to change code in three places (three that i noticed) but whatever

**Comment by bogderp** [comment]
fixed in c7b368183a0efa921eec0b21114020c6c7e2337d
