### ISSUE TITLE
RSVP question choices not centered

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Website#37]
firefox 43, linux x64
![screenshot](https://cloud.githubusercontent.com/assets/1198161/12499982/112d8d6e-c07d-11e5-8b2c-6692f56eede6.png)

**Comment by bogderp** [comment]
I believe this is a newly introduced bug by firefox. It does not handle justify-content: space-around properly

**Comment by bogderp** [comment]
fixed in 5699c4397de4120c81501071e114b2e6996ea86c using unconventional means
