### ISSUE TITLE
Mentorship page: when your saved value is "No", click "No" and submit the form

### ISSUE THREAD

**Issue by mhammerly** [SpartaHack/SpartaHack2016-Website#38]
500 errors for days

**Comment by mhammerly** [comment]
if you then reload /mentorship/register the prefilled value is "yes"

**Comment by mhammerly** [comment]
you then have to click different buttons a few times to get the categories question to show up

**Comment by bogderp** [comment]
fixed in 6d272ea05d8e6878e610780b7bdf8ea011298bfb
