### ISSUE TITLE
Extra blank text box

### ISSUE THREAD

**Issue by cnmcgrath** [SpartaHack/SpartaHack2016-Website#4]
<img width="1680" alt="screen shot 2015-11-04 at 7 25 17 pm" src="https://cloud.githubusercontent.com/assets/3112711/10956457/ea70965c-8329-11e5-8da5-0b6f1ab5577b.png">

in the past hackathon selection view 

Mac OS X 10.11.2 Beta Chrome

**Comment by bogderp** [comment]
That blank is a text box or searching. Looked into adding a placeholder, Select.JS does not seem to allow it.
