### ISSUE TITLE
'2016' text styling on error page

### ISSUE THREAD

**Issue by daniellescherr** [SpartaHack/SpartaHack2016-Website#6]
using safari on mac. 
entered bad data (email: @@@ password:123456) and got error 500 page as shown
<img width="990" alt="screen shot 2015-11-04 at 7 24 59 pm" src="https://cloud.githubusercontent.com/assets/11857236/10956451/dd486b1c-8329-11e5-9e8e-de554003bcb7.png">

**Comment by bogderp** [comment]
I has fixed this
