### ISSUE TITLE
When you turn off JS, the forms are not labeled

### ISSUE THREAD

**Issue by laurenbretz** [SpartaHack/SpartaHack2016-Website#9]
![screen shot 2015-11-04 at 7 28 07 pm](https://github-cloud.s3.amazonaws.com/assets%2F4753114%2F10956519%2F48f74a4a-832a-11e5-9fa3-6a9075e946b8.png)

**Comment by bogderp** [comment]
JS is an essential element of the application. It is now required before proceeding to apply, login, or view your application. A page notifying the user that we require JS is displayed if we detect JS is disabled.
